#getting base image
#FROM SCRATCH building image from scratch
FROM ubuntu

MAINTAINER acebesdexter <acebesdexter@gmail.com>

RUN apt-get update

CMD ["echo", "Hello World...! from my first docker image."]




#I added some spaces wew!